// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrlbiyxsF_PkUVT5RuS5UsqPKJHj8_WIc',
    appId: '1:486194141085:web:b038f51eaf4c17644c8174',
    messagingSenderId: '486194141085',
    projectId: 'masken',
    authDomain: 'masken-baee6.firebaseapp.com',
    storageBucket: 'masken.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK7SZhTbci2zZVLVhs-FJEQ-KiG6WKMKA',
    appId: '1:486194141085:android:56b1785ac4bb97c34c8174',
    messagingSenderId: '486194141085',
    projectId: 'masken',
    storageBucket: 'masken.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_YvO-APOIdcnKQPV99JJb3LXg3OC0EM',
    appId: '1:486194141085:ios:55cabaf18b893e3d4c8174',
    messagingSenderId: '486194141085',
    projectId: 'masken',
    storageBucket: 'masken.firebasestorage.app',
    iosBundleId: 'com.example.masken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_YvO-APOIdcnKQPV99JJb3LXg3OC0EM',
    appId: '1:486194141085:ios:55cabaf18b893e3d4c8174',
    messagingSenderId: '486194141085',
    projectId: 'masken',
    storageBucket: 'masken.firebasestorage.app',
    iosBundleId: 'com.example.masken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrlbiyxsF_PkUVT5RuS5UsqPKJHj8_WIc',
    appId: '1:486194141085:web:7b4e660265d410104c8174',
    messagingSenderId: '486194141085',
    projectId: 'masken',
    authDomain: 'masken-baee6.firebaseapp.com',
    storageBucket: 'masken.firebasestorage.app',
  );
}
